# Generated by Django 4.0.3 on 2022-06-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('RelationID', models.AutoField(max_length=45, primary_key=True, serialize=False)),
                ('FriendMaster', models.CharField(max_length=45)),
                ('FriendID', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'FriendList',
            },
        ),
        migrations.CreateModel(
            name='PillList',
            fields=[
                ('ModuleNum', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('PillMaster', models.CharField(max_length=45)),
                ('PillName', models.CharField(max_length=45)),
                ('PillAmount', models.CharField(max_length=45)),
                ('PillTime', models.CharField(max_length=45)),
                ('PillEat', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PillTake',
            fields=[
                ('idPillTake', models.AutoField(primary_key=True, serialize=False)),
                ('ModuleNum', models.CharField(max_length=45)),
                ('PillTakeTime', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PillTime',
            fields=[
                ('idPillTime', models.AutoField(primary_key=True, serialize=False)),
                ('ModuleNum', models.CharField(max_length=45)),
                ('PillName', models.CharField(max_length=45)),
                ('PillMaster', models.CharField(max_length=45)),
                ('EatTime', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserMember',
            fields=[
                ('userID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('userPW', models.CharField(max_length=45)),
                ('userNAME', models.CharField(max_length=45)),
                ('userTEL', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
