# Generated by Django 4.0.3 on 2022-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_friend_friendid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='FriendID',
            field=models.CharField(max_length=45),
        ),
    ]
