# Generated by Django 4.0.3 on 2022-06-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_alter_friend_friendid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='FriendID',
            field=models.ForeignKey(db_column='FriendID', on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='pybo.usermember'),
        ),
    ]
